[workspace]
resolver = "2"
members = [
    "crates/flume-core",
    "crates/flume-runtime",
    "crates/flume-api",
    "crates/flume-state",
    "crates/flume-connectors/flume-connector-file",
    "crates/flume-connectors/flume-connector-tcp",
    "crates/flume-connectors/flume-connector-kafka",
    "crates/flume-network",
    "crates/flume-server",
]

[workspace.package]
edition = "2024"
rust-version = "1.93"
license = "MIT"
