[package]
name = "flume-state"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bitcode = { version = "0.6", features = ["serde"] }
flume-core = { path = "../flume-core", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
criterion = "0.8"
proptest = "1"

[[bench]]
name = "serde"
harness = false
