[package]
name = "flume-runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
perf = ["core_affinity"]

[dependencies]
flume-core = { path = "../flume-core", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync", "rt", "macros", "time", "fs"] }
tokio-util = "0.7"
tracing = "0.1"
metrics = "0.24"
ahash = "0.8"
crossbeam-utils = "0.8"
core_affinity = { version = "0.8", optional = true }

[dev-dependencies]
bitcode = { version = "0.6", features = ["serde"] }
tempfile = "3"
criterion = "0.5"
metrics-util = "0.18"
tokio = { version = "1", features = ["sync", "rt", "macros", "time", "fs", "rt-multi-thread"] }

[[bench]]
name = "channel"
harness = false

[[bench]]
name = "throughput"
harness = false

[[bench]]
name = "latency"
harness = false
